rule all:
  input: "Eve_baton.txt"

rule Eve:
  input: "Dave_baton.txt"
  output: "Eve_baton.txt"
  shell: "sleep 5; cat {input} > {output}; echo 'Eve passes baton' >> {output};"

rule Dave:
  input: "Cathy_baton.txt"
  output: "Dave_baton.txt"
  shell: "sleep 5; cat {input} > {output}; echo 'Dave passes baton' >> {output};"

rule Cathy:
  input: "Bob_baton.txt"
  output: "Cathy_baton.txt"
  shell: "sleep 5; cat {input} > {output}; echo 'Cathy passes baton' >> {output};"

rule Bob:
  input: "Alice_baton.txt"
  output: "Bob_baton.txt"
  shell: "sleep 5; cat {input} > {output}; echo 'Bob passes baton' >> {output};"

rule Alice:
  output: "Alice_baton.txt"
  shell: "sleep 5; echo 'Alice passes baton' > {output}"



